name: test_task
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_svg: ^1.1.6
  flutter_bloc: ^8.1.2

  auto_route: ^5.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

  hive_generator: ^2.0.0
  auto_route_generator: ^5.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/static/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/static/Montserrat-Light.ttf
          weight: 300

    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/static/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish/static/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish/static/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish/static/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish/static/Mulish-Light.ttf
          weight: 300

